#!/bin/bash

STDOUT=/dev/fd/1
STDERR=/dev/fd/2

export STDOUT STDERR

ACTIVE=1

_term() {
  if [ "$ACTIVE" = "1" ]; then
    ACTIVE=
    echo "Caught SIGTERM signal. Stopping everything"
    /opt/eva/sbin/eva-control stop
    /opt/eva/sbin/registry-control stop
  fi
  exit 0
}

trap _term SIGTERM

SETUP_MODE=
FIRST_RUN=

cd /opt/eva || exit 1


[ -d /mnt/var ] && rm -rf /opt/eva/var && ln -sf /mnt/var /opt/eva/var

./sbin/registry-control start

if [ ! -f /.setup_completed ]; then
  SETUP_MODE=1
  if [ -f /setup/prepare.sh ]; then
    cd /setup || exit 1
    ./prepare.sh || exit $?
    cd /opt/eva || exit 1
  fi
  if [ -f /setup/rc.local ]; then
    cp -vf /setup/rc.local /etc/
    chmod +x /etc/rc.local
  fi
  for vol in log backup; do
    [ -d /mnt/${vol} ] && rm -rf /opt/eva/${vol} && ln -sf /mnt/${vol} /opt/eva/${vol}
  done
  for vol in runtime ui pvt etc; do
    if [ -d /mnt/${vol} ]; then
      if [ -z "$(ls -A /mnt/${vol})" ]; then
        # empty, putting defaults
        mv /opt/eva/${vol}/* /mnt/${vol}/
      fi
      rm -rf /opt/eva/${vol}
      ln -sf /mnt/${vol} /opt/eva/${vol}
    fi
  done
  . ./etc/eva_config
  if [ "$SYSTEM_NAME" = "eva_changeme" ]; then
    SYSTEM_NAME=$(hostname)
    FIRST_RUN=1
    ./bin/eva feature setup node_name "name=${SYSTEM_NAME},rename_only=1" || exit 1
    rm -f ./etc/eva_config-[0-9]*
    [ -z "$MASTERKEY" ] && MASTERKEY=$( (tr -cd '[:alnum:]' < /dev/urandom | head -c64) 2>/dev/null)
    [ -z "$DEFAULTKEY" ] && DEFAULTKEY=$( (tr -cd '[:alnum:]' < /dev/urandom | head -c64) 2>/dev/null)
    ./bin/eva masterkey set "${MASTERKEY}" > /dev/null || exit 1
    for c in uc lm sfa; do
      ./sbin/apikey-set $c default "${DEFAULTKEY}" || exit 1
    done
  else
    ./bin/eva feature setup venv
  fi
  MY_BUILD=$(./sbin/eva-tinyapi -B)
  source <(./sbin/key-as-source data/info)
  [ -z "$MY_BUILD" ] && exit 12
  [ -z "$BUILD" ] && exit 12
  if [ "$MY_BUILD" -lt "$BUILD" ]; then
    echo "FATAL. Container downgrade is not allowed"
    exit 13
  elif [ "$MY_BUILD" -gt "$BUILD" ]; then
    ./update.sh || exit 13
  fi
  rm -f update.sh
fi

[ -x /etc/rc.local ] && /etc/rc.local

/opt/eva/sbin/eva-control start || exit 1

if [ "$SETUP_MODE" = "1" ]; then
  if [ -f /setup/setup.sh ]; then
    cd /setup || exit 1
    ./setup.sh || exit $?
    cd /opt/eva || exit 1
  fi
  touch /.setup_completed
  if [ "$FIRST_RUN" = "1" ]; then
    echo
    echo "Setup completed"
    echo
    echo "Master key: ${MASTERKEY}"
    echo "Default key: ${DEFAULTKEY}"
    echo
    if [ "${DEPLOY}" ]; then
      echo "Starting deployment of ${DEPLOY}..."
      ./bin/eva sfa cloud deploy "${DEPLOY}" -s -y -c "srv=${SYSTEM_NAME}"
    fi
  fi
fi

while [ "${ACTIVE}" = "1" ]; do
  sleep 1
done
exit 0
