#!/bin/sh

for p in uc lm sfa; do
  AUTO_PREFIX=1 ./sbin/eva-registry-cli \
    set-field config/${p}/main server/log-stdout true -p boolean > /dev/null || exit 1
  AUTO_PREFIX=1 ./sbin/eva-registry-cli \
    set-field config/${p}/service stdout /proc/1/fd/1 > /dev/null || exit 1
  AUTO_PREFIX=1 ./sbin/eva-registry-cli \
    set-field config/${p}/service stderr /proc/1/fd/2 > /dev/null || exit 1
done
exit 0
